baseURL                = "https://scaledagiledevops.com/"
defaultContentLanguage = "en"
enableEmoji            = false
enableGitInfo          = true
metaDataFormat         = "yaml"
publishDir             = "public"

title = 'Enterprise transformation without the risk of culture change!'

googleAnalytics = "G-BT3HZK3PLP"

copyright    = "Creative Commons 4.0, Non-commercial use with attribution"
copyrightUrl = "https://creativecommons.org/licenses/by-nc-sa/4.0/"

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min      = "0.73.0"
  [[module.imports]]
    disable = false
    path    = "github.com/google/docsy"

[taxonomies]
  category = "categories"
  tag      = "tags"

[outputs]
  home = [
    "HTML",
    "JSON"
  ]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    endLevel   = 6
    ordered    = false
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe = false

[params]
  # Website logo file paths
  logo      = "/images/sadmf-logo-wide.png"
  logoTouch = "images/sadmf-logo-wide.png"
  # Image file path displayed during a 404 error
  image404 = "images/404.gif"
  # Favicon website file path
  favicon = "images/favicon.png"
  # Default layout used for the homepage
  # homeLayout              = "onboarding"
  homeLayout = "sadmf"
  # Site content order (https://gohugo.io/templates/lists/#order-content)
  siteContentOrder = "weight"
  # Activate/Deactivate the table of contents globally (sitewide)
  toc = true
  # Activate a global banner on all website pages
  globalBanner = false
  # Current version of the website
  currentVersion = "latest"
  # Url of the latest version of the website
  latestVersionUrl = "https://scaledagiledevops.com/"
  # Enforce Link resolution using relref function (https://gohugo.io/content-management/cross-references/)
  enforceRefrelLinks = false
  # Keyboard shortcuts list
  # For each shortcut following keys must be sets:
  # - keys     = [Keyboard shortcuts table](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values)
  # - function = "Javascript function name to call by the shortcut"
  #   [[params.navbar.shortcuts]]
  # name = "<i class='fa-solid fa-users-gear'></i> PeopleWare"
  # url = "peopleware"
  [params.navbar.shortcuts]
    # Example shortcut definition
    [params.navbar.shortcuts.example]
      function = "scExample"
      keys = [
        "1",
        "Shift"
      ]
# Taxonomies list
# For each taxonomy following keys can be sets:
# - icon = "Fontawesome classes associated to the taxonomy"
[params.taxonomies]
  [params.taxonomies.categories]
    icon = "fa-solid fa-table-cells"
    # Assets list (https://gohugo.io/hugo-pipes/resource-from-template/) to include
    # Managed assets:
    # - sass                  = [List of SASS files]
    # - css                   = [List of CSS files]
    # - js                    = [List of javascript files]
    # - jsModules             = [List of javascript modules]
    # - shortcodes.css        = [List of CSS files to includes when the associated shortcode exist in the page content]
    # - shortcodes.js         = [List of javascript files to includes when the associated shortcode exist in the page content]
    # - shortcodes.jsModules  = [List of javascript module files to includes when the associated shortcode exist in the page content]
    # - fencedcodes.css       = [List of CSS files to includes when the associated language of fenced code exist in the page content]
    # - fencedcodes.js        = [List of javascript files to includes when the associated language of fenced code exist in the page content]
    # - fencedcodes.jsModules = [List of javascript module files to includes when the associated language of fenced code exist in the page content]
    #

[params.includes]
  css = [
    "css/button.css",
    "css/fontawesome6.min.css",
    "css/overrides.css"
  ]
